# Welcome to Jekyll!

# Site settings
title: chengzi's blog
email: chengzi12130@gmail.com
description: hello world
twitter_username: iichengzi
github_username:  ichengzi

timezone: Asia/Shanghai
# Build settings
markdown: kramdown
kramdown:
  input: GFM
# highlighter: pygments

# theme: jekyll-theme-cayman

exclude: bootstrap_course,html-js-learn,node-learn

paginate: 15
paginate_path: "page:num"