@startuml demo
actor Foo1
boundary Foo2
control Foo3
entity  Foo4
database Foo5
collections Foo6

Foo1 -> Foo2 : To boundary
Foo1 -> Foo3 : To Control
Foo1 -> Foo4 : To Entity
Foo1 -> Foo5 : To Database
Foo1 -> Foo6 : To collections
@enduml